# Generated by Django 4.2 on 2024-03-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleportDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fecha', models.TextField()),
                ('hora', models.TextField()),
                ('usuario', models.TextField()),
                ('hashtags', models.TextField()),
            ],
        ),
    ]
