# Generated by Django 4.2 on 2024-03-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teleportdatabase',
            old_name='fecha',
            new_name='fechayhora',
        ),
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='hora',
        ),
    ]
