# Generated by Django 4.2 on 2024-03-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0002_rename_fecha_teleportdatabase_fechayhora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleportdatabase',
            name='userid',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
