# Generated by Django 4.2 on 2024-03-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0003_teleportdatabase_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleportdatabase',
            name='enlace',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teleportdatabase',
            name='hashtags',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
