# Generated by Django 4.2 on 2024-03-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0004_teleportdatabase_enlace_teleportdatabase_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='hashtags',
        ),
    ]
