# Generated by Django 4.2 on 2024-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0005_remove_teleportdatabase_enlace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='fechayhora',
        ),
        migrations.AddField(
            model_name='teleportdatabase',
            name='fecha',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teleportdatabase',
            name='hora',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
