# Generated by Django 4.2 on 2024-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0006_remove_teleportdatabase_fechayhora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleportdatabase',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
