# Generated by Django 4.2.11 on 2024-04-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0007_teleportdatabase_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='teleportdatabase',
            name='hora',
        ),
        migrations.AddField(
            model_name='teleportdatabase',
            name='fechayhora',
            field=models.TextField(default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
