# Generated by Django 4.2.11 on 2024-04-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleport_app', '0008_remove_teleportdatabase_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleportdatabase',
            name='fecha_hora_cad',
            field=models.TextField(default='2021-01-01 13:00:00'),
            preserve_default=False,
        ),
    ]
